name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-20.04, windows-2019, macos-11]
        os: [ubuntu-20.04, windows-2019]

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3
      - name: Checkout submodules
        run: git submodule update --init --recursive 
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.3
        # env:
        #   CIBW_SOME_OPTION: value
        #    ...
        # env:
        #  CIBW_PLATFORM: ${{ matrix.os }}
        with:
          package-dir: .
          output-dir: wheelhouse
          config-file: "{package}/pyproject.toml"
          only: ${{ matrix.os }}

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

